In [2]:
import torch
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 


In [3]:
data=pd.read_csv('train-sample.csv')
data.head(10)

PostId     PostCreationDate  OwnerUserId    OwnerCreationDate  \
0   6046168  05/18/2011 14:14:05       543315  09/17/2010 10:15:06   
1   4873911  02/02/2011 11:30:10       465076  10/03/2010 09:30:58   
2   3311559  07/22/2010 17:21:54       406143  07/22/2010 16:58:20   
3   9990413  04/03/2012 09:18:39       851755  07/19/2011 10:22:40   
4  10421966  05/02/2012 21:25:01       603588  02/04/2011 18:05:34   
5   8616154  12/23/2011 12:36:28       787158  06/07/2011 09:13:37   
6   1520973  10/05/2009 16:10:03        80229  03/19/2009 21:13:16   
7   5528942  04/03/2011 10:12:59       667355  03/19/2011 14:04:57   
8   4344698  12/03/2010 10:37:44       447244  09/01/2010 09:10:05   
9   7910832  10/27/2011 01:37:33      1015681  10/27/2011 01:28:41   

   ReputationAtPostCreation  OwnerUndeletedAnswerCountAtPostTime  \
0                         1                                    2   
1                       192                                   24   
2                         1                                    0   
3                         4                                    1   
4                       334                                   14   
5                        20                                    0   
6                        95                                   10   
7                        32                                    0   
8                         1                                    0   
9                         1                                    0   

                                               Title  \
0  For Mongodb is it better to reference an objec...   
1  How to insert schemalocation in a xml document...   
2                            Too many lookup tables    
3                    What is this PHP code in VB.net   
4  Spring-Data mongodb querying multiple classes ...   
5  stop ajax function in midway when other elemen...   
6             Regex to detect Javascript In a string   
7                              List of all .txt file   
8  I want to design an invitation card for my wed...   
9  VB Script To Delete Header and Footer plus App...   

                                        BodyMarkdown             Tag1  \
0  I am building a corpus of indexed sentences in...          mongodb   
1  i create a xml document with JAXP and search a...              dom   
2  What are the adverse effects of having too man...       sql-server   
3  I am looking for the vb.net equivalent of this...              php   
4  With Spring-Data, you can use the @Document an...          mongodb   
5  Hi have a page which has List data. \r\n\r\nWh...           jquery   
6  I am trying to detect JavaScript in my queryst...            regex   
7  I want to write a program that give a path in ...              c++   
8  I want to make an Application in Silverlight f...  silverlight-4.0   
9  Hi All VB Script Gurus,\r\n\r\nI am new to VB ...               vb   

              Tag2   Tag3        Tag4 Tag5       PostClosedDate  \
0              NaN    NaN         NaN  NaN                  NaN   
1              xsd   jaxp         NaN  NaN                  NaN   
2  database-design  enums         NaN  NaN                  NaN   
3           vb.net    NaN         NaN  NaN  04/15/2012 21:12:48   
4      spring-data    NaN         NaN  NaN                  NaN   
5             ajax    NaN         NaN  NaN                  NaN   
6              xss     c#  javascript  NaN                  NaN   
7                c     qt         qt4  NaN  04/07/2011 05:46:46   
8              NaN    NaN         NaN  NaN  01/08/2012 21:15:49   
9              NaN    NaN         NaN  NaN  10/27/2011 03:24:58   

            OpenStatus  
0                 open  
1                 open  
2                 open  
3        too localized  
4                 open  
5                 open  
6                 open  
7  not a real question  
8        too localized  
9        too localized

In [4]:
data.columns

Index(['PostId', 'PostCreationDate', 'OwnerUserId', 'OwnerCreationDate',
       'ReputationAtPostCreation', 'OwnerUndeletedAnswerCountAtPostTime',
       'Title', 'BodyMarkdown', 'Tag1', 'Tag2', 'Tag3', 'Tag4', 'Tag5',
       'PostClosedDate', 'OpenStatus'],
      dtype='object')

In [5]:
data['OpenStatus'].value_counts()

OpenStatus
open                   70136
not a real question    30789
off topic              17530
not constructive       15659
too localized           6158
Name: count, dtype: int64

In [6]:
data_train=data[['Title','BodyMarkdown','OpenStatus']]
data_train.head()

Title  \
0  For Mongodb is it better to reference an objec...   
1  How to insert schemalocation in a xml document...   
2                            Too many lookup tables    
3                    What is this PHP code in VB.net   
4  Spring-Data mongodb querying multiple classes ...   

                                        BodyMarkdown     OpenStatus  
0  I am building a corpus of indexed sentences in...           open  
1  i create a xml document with JAXP and search a...           open  
2  What are the adverse effects of having too man...           open  
3  I am looking for the vb.net equivalent of this...  too localized  
4  With Spring-Data, you can use the @Document an...           open

In [7]:
data_train.shape


(140272, 3)

Its too big, lets take just 1k rows

In [8]:
data_train=data_train.sample(10000,random_state=42)
data_train.head()

Title  \
44074                      Hidden Features of JavaScript   
103977  Silverlight on Mac - how to debug a Memory Leak?   
130482                                  php include path   
51655                           C - Array of Char Arrays   
86035                         If conditon is not working   

                                             BodyMarkdown        OpenStatus  
44074   **What "Hidden Features" of JavaScript do you ...  not constructive  
103977  I've written a Silverlight app that works as a...              open  
130482  here I am really confused. ![enter image descr...     too localized  
51655   Im trying to work with the example in the K an...              open  
86035   I have written a conditonal if for checking wh...              open

In [9]:
data_train.shape

(10000, 3)

In [10]:
data_train['OpenStatus'].value_counts()

OpenStatus
open                   4951
not a real question    2234
off topic              1258
not constructive       1109
too localized           448
Name: count, dtype: int64

Texthero is a preprocessing python toolkit.
It does many things, They are: 
fillna()
lowercase()
remove_digits()
remove_punctuation()
remove_diacritics()
remove_stopwords()
remove_whitespace()

In [11]:
import texthero as hero

data_train['Title'] = hero.clean(data_train['Title'])
data_train['BodyMarkdown'] = hero.clean(data_train['BodyMarkdown'])


In [12]:
data_train.head()

Title  \
44074          hidden features javascript   
103977  silverlight mac debug memory leak   
130482                   php include path   
51655                 c array char arrays   
86035                    conditon working   

                                             BodyMarkdown        OpenStatus  
44074   hidden features javascript think every program...  not constructive  
103977  written silverlight app works uploader amazon ...              open  
130482  really confused enter image description folder...     too localized  
51655   im trying work example k r book topic struggli...              open  
86035   written conditonal checking whether string fkl...              open

In [13]:
# lets change the target to number
data_train['OpenStatus']=data_train['OpenStatus'].map({'open':0,
                                                         'not a real question':1,
                                                         'off topic':2,
                                                         'not constructive':3,
                                                         'too localized':4
                                                         }) 
data_train.head()

Title  \
44074          hidden features javascript   
103977  silverlight mac debug memory leak   
130482                   php include path   
51655                 c array char arrays   
86035                    conditon working   

                                             BodyMarkdown  OpenStatus  
44074   hidden features javascript think every program...           3  
103977  written silverlight app works uploader amazon ...           0  
130482  really confused enter image description folder...           4  
51655   im trying work example k r book topic struggli...           0  
86035   written conditonal checking whether string fkl...           0

In [14]:
# let's separate X and y
X=data_train['Title'] + ' '+ data_train['BodyMarkdown']
y=data_train['OpenStatus']

In [15]:
print(y)

44074     3
103977    0
130482    4
51655     0
86035     0
         ..
10082     0
13921     0
64615     0
96697     3
51728     0
Name: OpenStatus, Length: 10000, dtype: int64


In [16]:
X.shape

(10000,)

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=41)

In [18]:
print(y_train)

132336    0
90563     1
2154      1
77161     0
44950     2
         ..
29273     0
137008    0
35459     0
28966     0
76560     3
Name: OpenStatus, Length: 8000, dtype: int64


In [19]:
X_train.shape

(8000,)

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()  # it contains only 10k features (fixed!)

X_train = vectorizer.fit_transform(X_train).toarray()  # converting words to numbers for train data 
X_test= vectorizer.transform(X_test).toarray()    # converting words to numbers for test data 

In [21]:
X_train.shape

(8000, 43486)

In [22]:
y_train.shape

(8000,)

In [23]:
# Naive Bayes 
from sklearn.naive_bayes import GaussianNB
clf=GaussianNB()
clf.fit(X_train,y_train)

GaussianNB()

In [24]:
predicted_naive=clf.predict(X_test)

In [25]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print('Accuracy score ',accuracy_score(predicted_naive,y_test))
print('confusion matrix',confusion_matrix(predicted_naive,y_test))
print('Classification report ',classification_report(predicted_naive,y_test))


Accuracy score  0.4435
confusion matrix [[684 184  99  91  57]
 [117  81  25  22  16]
 [ 73  45  69  22   5]
 [ 88  79  45  51   8]
 [ 63  58   9   7   2]]
Classification report                precision    recall  f1-score   support

           0       0.67      0.61      0.64      1115
           1       0.18      0.31      0.23       261
           2       0.28      0.32      0.30       214
           3       0.26      0.19      0.22       271
           4       0.02      0.01      0.02       139

    accuracy                           0.44      2000
   macro avg       0.28      0.29      0.28      2000
weighted avg       0.46      0.44      0.45      2000



In [26]:
#MLP classification 
from sklearn.neural_network import MLPClassifier
mlp_clf=MLPClassifier(early_stopping=True, verbose=2)
mlp_clf.fit(X_train,y_train)

Iteration 1, loss = 1.51050017
Validation score: 0.461250
Iteration 2, loss = 1.21714576
Validation score: 0.471250
Iteration 3, loss = 1.01502308
Validation score: 0.548750
Iteration 4, loss = 0.81680629
Validation score: 0.582500
Iteration 5, loss = 0.63795648
Validation score: 0.587500
Iteration 6, loss = 0.49103718
Validation score: 0.576250
Iteration 7, loss = 0.37540281
Validation score: 0.567500
Iteration 8, loss = 0.28736649
Validation score: 0.563750
Iteration 9, loss = 0.22221402
Validation score: 0.563750
Iteration 10, loss = 0.17406007
Validation score: 0.566250
Iteration 11, loss = 0.13824609
Validation score: 0.563750
Iteration 12, loss = 0.11124122
Validation score: 0.553750
Iteration 13, loss = 0.09085534
Validation score: 0.556250
Iteration 14, loss = 0.07540654
Validation score: 0.552500
Iteration 15, loss = 0.06327653
Validation score: 0.542500
Iteration 16, loss = 0.05364444
Validation score: 0.543750
Validation score did not improve more than tol=0.000100 for 10 co

MLPClassifier(early_stopping=True, verbose=2)

In [27]:
predicted_mlp=mlp_clf.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print('Accuracy score ',accuracy_score(predicted_mlp,y_test))
print('confusion matrix',confusion_matrix(predicted_mlp,y_test))
print('Classification report ',classification_report(predicted_mlp,y_test))

Accuracy score  0.6095
confusion matrix [[890 248 101  64  66]
 [ 84 159  23  28  17]
 [ 25  20  80  11   1]
 [ 26  20  43  90   4]
 [  0   0   0   0   0]]
Classification report                precision    recall  f1-score   support

           0       0.87      0.65      0.74      1369
           1       0.36      0.51      0.42       311
           2       0.32      0.58      0.42       137
           3       0.47      0.49      0.48       183
           4       0.00      0.00      0.00         0

    accuracy                           0.61      2000
   macro avg       0.40      0.45      0.41      2000
weighted avg       0.71      0.61      0.65      2000



c:\Users\user\anaconda3\envs\env_python3.9\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\anaconda3\envs\env_python3.9\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\anaconda3\envs\env_python3.9\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [29]:
# Logistic Regression 
from sklearn.linear_model import LogisticRegression
model_lr=LogisticRegression(max_iter=1000)
model_lr.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [30]:
predicted_lr=model_lr.predict(X_test)

In [31]:
print('Accuracy score ',accuracy_score(predicted_lr,y_test))
print('confusion matrix',confusion_matrix(predicted_lr,y_test))
print('Classification report ',classification_report(predicted_lr,y_test))

Accuracy score  0.5885
confusion matrix [[911 294 134  75  71]
 [ 71 126  16  29  12]
 [ 22  13  60  10   1]
 [ 21  14  37  79   3]
 [  0   0   0   0   1]]
Classification report                precision    recall  f1-score   support

           0       0.89      0.61      0.73      1485
           1       0.28      0.50      0.36       254
           2       0.24      0.57      0.34       106
           3       0.41      0.51      0.46       154
           4       0.01      1.00      0.02         1

    accuracy                           0.59      2000
   macro avg       0.37      0.64      0.38      2000
weighted avg       0.74      0.59      0.64      2000



In [32]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.pipeline import Pipeline

neig=np.arange(1,25)
train_accuracy = []
test_accuracy = []

for k in neig:
    knn = KNeighborsClassifier(n_neighbors=k)
    model = Pipeline([
        
        ('tfidf', TfidfTransformer()),
        ('model', knn)
    ])
    
    model.fit(X_train, y_train)
    train_accuracy.append(model.score(X_train, y_train))
    test_accuracy.append(model.score(X_test, y_test))

best_k = np.argmax(test_accuracy) + 1
best_accuracy = np.max(test_accuracy)
print("Best accuracy is {} with k={}".format(best_accuracy, best_k))


Best accuracy is 0.544 with k=22


In [33]:
print(classification_report(y_test,model.predict(X_test)))

              precision    recall  f1-score   support

           0       0.58      0.87      0.70      1025
           1       0.34      0.21      0.26       447
           2       0.48      0.16      0.24       247
           3       0.49      0.28      0.36       193
           4       0.00      0.00      0.00        88

    accuracy                           0.54      2000
   macro avg       0.38      0.31      0.31      2000
weighted avg       0.48      0.54      0.48      2000



c:\Users\user\anaconda3\envs\env_python3.9\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\anaconda3\envs\env_python3.9\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\user\anaconda3\envs\env_python3.9\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [34]:
#Xgboost
from scipy.stats import uniform
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier

param_dist={"learning_rate":uniform(0,2),
            "gamma":uniform(1,0.000001),
            "max_depth":range(1,50),
            "n_estimators":range(1,300),
            "min_child_weight":range(1,10),
            'n_jobs':range(1,5)
            }
rs=RandomizedSearchCV(XGBClassifier(),param_distributions=param_dist,n_iter=3)

In [35]:

model=Pipeline([
                ('tfidf',TfidfTransformer()),
                ('model',rs)])

In [36]:
model.fit(X_train,y_train)


Pipeline(steps=[('tfidf', TfidfTransformer()),
                ('model',
                 RandomizedSearchCV(estimator=XGBClassifier(base_score=None,
                                                            booster=None,
                                                            callbacks=None,
                                                            colsample_bylevel=None,
                                                            colsample_bynode=None,
                                                            colsample_bytree=None,
                                                            device=None,
                                                            early_stopping_rounds=None,
                                                            enable_categorical=False,
                                                            eval_metric=None,
                                                            feature_types=None,
                                                            gamma=None,
                                                            grow_policy=None,
                                                            importance_typ...
                                                            random_state=None, ...),
                                    n_iter=3,
                                    param_distributions={'gamma': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000001F2B1D51670>,
                                                         'learning_rate': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000001F2B7049E20>,
                                                         'max_depth': range(1, 50),
                                                         'min_child_weight': range(1, 10),
                                                         'n_estimators': range(1, 300),
                                                         'n_jobs': range(1, 5)}))])

In [37]:
predicted_xgboost=model.predict(X_test)
print('Accuracy score',accuracy_score(predicted_xgboost,y_test))
print('confusion matrix',confusion_matrix(predicted_xgboost,y_test))
print('Classification report',classification_report(predicted_xgboost,y_test))

Accuracy score 0.5875
confusion matrix [[820 202 108  53  55]
 [139 202  38  39  20]
 [ 38  17  68  21   6]
 [ 27  23  33  80   2]
 [  1   3   0   0   5]]
Classification report               precision    recall  f1-score   support

           0       0.80      0.66      0.72      1238
           1       0.45      0.46      0.46       438
           2       0.28      0.45      0.34       150
           3       0.41      0.48      0.45       165
           4       0.06      0.56      0.10         9

    accuracy                           0.59      2000
   macro avg       0.40      0.52      0.41      2000
weighted avg       0.65      0.59      0.61      2000

